//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahCoadz.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataShort1
    {
        public int ID { get; set; }
        public string MetaFlag { get; set; }
        public string MetaStruct { get; set; }
        public string StringIdx50A { get; set; }
        public string StringIdx50B { get; set; }
        public string StringIdx50C { get; set; }
        public string StringIdx50D { get; set; }
        public string StringIdx50E { get; set; }
        public string StringIdx100A { get; set; }
        public string String100A { get; set; }
        public string String100B { get; set; }
        public string String100C { get; set; }
        public string String100D { get; set; }
        public string String100E { get; set; }
        public Nullable<System.DateTime> DtIdxA { get; set; }
        public Nullable<System.DateTime> DtIdxB { get; set; }
        public Nullable<System.DateTime> DtA { get; set; }
        public Nullable<System.DateTime> DtB { get; set; }
        public Nullable<System.DateTime> DtC { get; set; }
        public Nullable<System.DateTime> DtD { get; set; }
        public Nullable<System.DateTime> DtE { get; set; }
        public Nullable<bool> BoolIdxA { get; set; }
        public Nullable<bool> BoolIdxB { get; set; }
        public Nullable<bool> BoolA { get; set; }
        public Nullable<bool> BoolB { get; set; }
        public Nullable<bool> BoolC { get; set; }
        public Nullable<bool> BoolD { get; set; }
        public Nullable<bool> BoolE { get; set; }
        public Nullable<decimal> MoneyIdxA { get; set; }
        public Nullable<decimal> MoneyIdxB { get; set; }
        public Nullable<decimal> MoneyA { get; set; }
        public Nullable<decimal> MoneyB { get; set; }
        public Nullable<decimal> MoneyC { get; set; }
        public Nullable<decimal> MoneyD { get; set; }
        public Nullable<decimal> MoneyE { get; set; }
        public Nullable<int> IntIdxA { get; set; }
        public Nullable<int> IntIdxB { get; set; }
        public Nullable<int> IntA { get; set; }
        public Nullable<int> IntB { get; set; }
        public Nullable<int> IntC { get; set; }
        public Nullable<int> IntD { get; set; }
        public Nullable<int> IntE { get; set; }
        public Nullable<decimal> DECIMALIdxA { get; set; }
        public Nullable<decimal> DECIMALIdxB { get; set; }
        public Nullable<decimal> DECIMALA { get; set; }
        public Nullable<decimal> DECIMALB { get; set; }
        public Nullable<decimal> DECIMALC { get; set; }
        public Nullable<decimal> DECIMALD { get; set; }
        public Nullable<decimal> DECIMALE { get; set; }
        public Nullable<short> IntSmallIdxA { get; set; }
        public Nullable<short> IntSmallIdxB { get; set; }
        public Nullable<short> IntSmallA { get; set; }
        public Nullable<short> IntSmallB { get; set; }
        public Nullable<short> IntSmallC { get; set; }
        public Nullable<short> IntSmallD { get; set; }
        public Nullable<short> IntSmallE { get; set; }
        public Nullable<long> IntBigIdxA { get; set; }
        public Nullable<long> IntBigIdxB { get; set; }
        public Nullable<long> IntBigA { get; set; }
        public Nullable<long> IntBigB { get; set; }
        public Nullable<long> IntBigC { get; set; }
        public Nullable<long> IntBigD { get; set; }
        public Nullable<long> IntBigE { get; set; }
        public Nullable<float> FloatIdxA { get; set; }
        public Nullable<float> FloatIdxB { get; set; }
        public Nullable<float> FloatA { get; set; }
        public Nullable<float> FloatB { get; set; }
        public Nullable<float> FloatC { get; set; }
        public Nullable<float> FloatD { get; set; }
        public Nullable<float> FloatE { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime MetaCreated { get; set; }
        public string MetaCreatedBy { get; set; }
        public System.DateTime MetaEdited { get; set; }
        public string MetaEditedBy { get; set; }
        public string String25A { get; set; }
        public string String25B { get; set; }
        public string String25C { get; set; }
        public string String25D { get; set; }
        public string String25E { get; set; }
        public string MemoA { get; set; }
        public string MemoB { get; set; }
        public string MemoC { get; set; }
        public string MemoD { get; set; }
        public string MemoE { get; set; }
        public string MemoF { get; set; }
    }
}
